from typing import Protocol
from uuid import UUID

from app.domain.ask.schemas import SavedMemoryRecord
from app.domain.captures.schemas import CaptureResponse
from app.domain.privacy.schemas import UserDataDeletionResult
from app.domain.products.schemas import ProductSnapshot
from app.domain.profiles.schemas import FitProfile, FitProfileUpdate
from app.domain.purchases.schemas import PurchaseRecord


class MizaajStore(Protocol):
    def initialize(self) -> None: ...

    def get_profile(self, user_id: UUID) -> FitProfile: ...

    def update_profile(self, user_id: UUID, payload: FitProfileUpdate) -> FitProfile: ...

    def delete_profile(self, user_id: UUID) -> FitProfile: ...

    def list_products(self) -> list[ProductSnapshot]: ...

    def get_product(self, product_id: UUID) -> ProductSnapshot: ...

    def save_product(self, product: ProductSnapshot) -> ProductSnapshot: ...

    def delete_product(self, product_id: UUID) -> ProductSnapshot: ...

    def save_capture(self, capture: CaptureResponse) -> CaptureResponse: ...

    def get_capture(self, capture_id: UUID) -> CaptureResponse: ...

    def list_captures(self, user_id: UUID) -> list[CaptureResponse]: ...

    def delete_capture(self, capture_id: UUID) -> CaptureResponse: ...

    def list_purchases(self, user_id: UUID) -> list[PurchaseRecord]: ...

    def get_purchase(self, purchase_id: UUID) -> PurchaseRecord: ...

    def save_purchase(self, purchase: PurchaseRecord) -> PurchaseRecord: ...

    def delete_purchase(self, purchase_id: UUID) -> PurchaseRecord: ...

    def list_saved_memories(self, user_id: UUID) -> list[SavedMemoryRecord]: ...

    def get_saved_memory(self, memory_id: UUID) -> SavedMemoryRecord: ...

    def save_memory_record(self, record: SavedMemoryRecord) -> SavedMemoryRecord: ...

    def delete_memory_record(self, memory_id: UUID) -> SavedMemoryRecord: ...

    def delete_saved_memories(self, user_id: UUID) -> int: ...

    def delete_user_data(self, user_id: UUID) -> UserDataDeletionResult: ...
